<?php

namespace ContainerUWseNmm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsole_Command_PublicAlias_Mailchimp_Mailchimppro_CustomerSyncService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'console.command.public_alias.mailchimp.mailchimppro.customer_sync' shared service.
     *
     * @return \PrestaChamps\MailchimpPro\Console\Commands\CustomersSyncCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['console.command.public_alias.mailchimp.mailchimppro.customer_sync'] = new \PrestaChamps\MailchimpPro\Console\Commands\CustomersSyncCommand();
    }
}
