<?php

namespace ContainerUWseNmm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInstallerService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShop\PsAccountsInstaller\Installer\Installer' shared autowired service.
     *
     * @return \PrestaShop\PsAccountsInstaller\Installer\Installer
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PrestaShop\\PsAccountsInstaller\\Installer\\Installer'] = new \PrestaShop\PsAccountsInstaller\Installer\Installer('7.1.2');
    }
}
