<?php

namespace ContainerUWseNmm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLegacyHeadTagService extends AdminKernelProdContainer
{
    /*
     * Gets the private 'PrestaShopBundle\Twig\Component\Legacy\LegacyHeadTag' autowired service.
     *
     * @return \PrestaShopBundle\Twig\Component\Legacy\LegacyHeadTag
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->factories['service_container']['PrestaShopBundle\\Twig\\Component\\Legacy\\LegacyHeadTag'] = function ($container) {
            $a = ($container->services['prestashop.router'] ?? $container->load('getPrestashop_RouterService'));

            if (isset($container->privates['PrestaShopBundle\\Twig\\Component\\Legacy\\LegacyHeadTag'])) {
                return $container->privates['PrestaShopBundle\\Twig\\Component\\Legacy\\LegacyHeadTag'];
            }

            return new \PrestaShopBundle\Twig\Component\Legacy\LegacyHeadTag(($container->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ??= new \PrestaShop\PrestaShop\Adapter\Configuration()), ($container->privates['PrestaShopBundle\\Twig\\Layout\\MenuBuilder'] ?? self::getMenuBuilderService($container)), ($container->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? self::getTranslatorInterfaceService($container)), ($container->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? self::getHookDispatcherService($container)), ($container->privates['PrestaShopBundle\\Twig\\Layout\\TemplateVariables'] ?? self::getTemplateVariablesService($container)), ($container->privates['PrestaShop\\PrestaShop\\Core\\Context\\CountryContext'] ?? self::getCountryContextService($container)), ($container->privates['PrestaShop\\PrestaShop\\Core\\Context\\ShopContext'] ?? self::getShopContextService($container)), ($container->privates['PrestaShop\\PrestaShop\\Core\\Context\\LanguageContext'] ?? self::getLanguageContextService($container)), ($container->privates['prestashop.default.language.context'] ?? self::getPrestashop_Default_Language_ContextService($container)), ($container->privates['PrestaShop\\PrestaShop\\Core\\Context\\CurrencyContext'] ?? self::getCurrencyContextService($container)), ($container->services['PrestaShop\\PrestaShop\\Core\\Context\\LegacyControllerContext'] ?? self::getLegacyControllerContextService($container)), ($container->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? self::getLegacyContextService($container)), $a);
        };

        return $container->factories['service_container']['PrestaShopBundle\\Twig\\Component\\Legacy\\LegacyHeadTag']($container);
    }
}
