<?php

namespace ContainerUWseNmm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMbo_SymfonyCacheClearerService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'mbo.symfony_cache_clearer' shared service.
     *
     * @return \PrestaShop\Module\Mbo\Service\MboSymfonyCacheClearer
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['mbo.symfony_cache_clearer'] = new \PrestaShop\Module\Mbo\Service\MboSymfonyCacheClearer();
    }
}
