<?php

namespace ContainerUWseNmm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStripeOfficial_ContextService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'stripe_official.context' shared service.
     *
     * @return \Context
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['stripe_official.context'] = \Context::getContext();
    }
}
