<?php

namespace ContainerUWseNmm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSpecificPriceControllerService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShopBundle\Controller\Admin\Sell\Catalog\Product\SpecificPriceController' shared autowired service.
     *
     * @return \PrestaShopBundle\Controller\Admin\Sell\Catalog\Product\SpecificPriceController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['PrestaShopBundle\\Controller\\Admin\\Sell\\Catalog\\Product\\SpecificPriceController'] = $instance = new \PrestaShopBundle\Controller\Admin\Sell\Catalog\Product\SpecificPriceController();

        $instance->setContainer(($container->privates['.service_locator.5V3iFzS'] ?? $container->load('get_ServiceLocator_5V3iFzSService'))->withContext('PrestaShopBundle\\Controller\\Admin\\Sell\\Catalog\\Product\\SpecificPriceController', $container));

        return $instance;
    }
}
