<?php

namespace ContainerUWseNmm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStripeOfficial_ModuleService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'stripe_official.module' shared service.
     *
     * @return \stripe_official
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['stripe_official.module'] = \Module::getInstanceByName('stripe_official');
    }
}
