<?php

namespace ContainerUWseNmm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStripeOfficial_PsAccountsFacadeService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'stripe_official.ps_accounts_facade' shared service.
     *
     * @return \PrestaShop\PsAccountsInstaller\Installer\Facade\PsAccounts
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['stripe_official.ps_accounts_facade'] = new \PrestaShop\PsAccountsInstaller\Installer\Facade\PsAccounts(($container->services['stripe_official.ps_accounts_installer'] ??= new \PrestaShop\PsAccountsInstaller\Installer\Installer('^7.0.9')));
    }
}
