<?php

namespace ContainerUWseNmm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSkipCloudSyncDependenciesControllerService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'StripeOfficial\Controllers\admin\SkipCloudSyncDependenciesController' shared service.
     *
     * @return \StripeOfficial\Controllers\admin\SkipCloudSyncDependenciesController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['StripeOfficial\\Controllers\\admin\\SkipCloudSyncDependenciesController'] = new \StripeOfficial\Controllers\admin\SkipCloudSyncDependenciesController($container);
    }
}
