<?php

namespace ContainerUWseNmm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStripeOfficial_PsAccountsInstallerService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'stripe_official.ps_accounts_installer' shared service.
     *
     * @return \PrestaShop\PsAccountsInstaller\Installer\Installer
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['stripe_official.ps_accounts_installer'] = new \PrestaShop\PsAccountsInstaller\Installer\Installer('^7.0.9');
    }
}
