<?php

namespace ContainerUWseNmm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTitleControllerService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShopBundle\Controller\Admin\Configure\ShopParameters\TitleController' shared autowired service.
     *
     * @return \PrestaShopBundle\Controller\Admin\Configure\ShopParameters\TitleController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['PrestaShopBundle\\Controller\\Admin\\Configure\\ShopParameters\\TitleController'] = $instance = new \PrestaShopBundle\Controller\Admin\Configure\ShopParameters\TitleController();

        $instance->setContainer(($container->privates['.service_locator.5V3iFzS'] ?? $container->load('get_ServiceLocator_5V3iFzSService'))->withContext('PrestaShopBundle\\Controller\\Admin\\Configure\\ShopParameters\\TitleController', $container));

        return $instance;
    }
}
