<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWqpwvjj\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWqpwvjj/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWqpwvjj.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWqpwvjj\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerWqpwvjj\appDevDebugProjectContainer([
    'container.build_hash' => 'Wqpwvjj',
    'container.build_id' => 'bb6e9718',
    'container.build_time' => 1586306093,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWqpwvjj');
