<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPpavkoq\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPpavkoq/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerPpavkoq.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerPpavkoq\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerPpavkoq\appProdProjectContainer([
    'container.build_hash' => 'Ppavkoq',
    'container.build_id' => '03eaf82e',
    'container.build_time' => 1586230085,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPpavkoq');
