{*
 * 2011-2018 OBSOLUTIONS WD S.L. All Rights Reserved.
 *
 * NOTICE:  All information contained herein is, and remains
 * the property of OBSOLUTIONS WD S.L. and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to OBSOLUTIONS WD S.L.
 * and its suppliers and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from OBSOLUTIONS WD S.L.
 *
 *  @author    OBSOLUTIONS WD S.L. <http://addons.prestashop.com/en/65_obs-solutions>
 *  @copyright 2011-2018 OBSOLUTIONS WD S.L.
 *  @license   OBSOLUTIONS WD S.L. All Rights Reserved
 *  International Registered Trademark & Property of OBSOLUTIONS WD S.L.
 *}
<div id="fieldset_3" class="panel">
	<div class="panel-heading">
		{l s='Automatic updates - How to configure cronjobs in Prestashop?' mod='obsstocks'}
	</div>

	<p>{l s='You can use the native prestashop module "Cronjobs" to create automatic processes. Use REAL URLs generated by this module to configure your cronjobs.' mod='obsstocks'}</p>
	
	{if $moduleCronsInstalled}
		<br/><a href="{$moduleCronLink nofilter}">{l s='Access to "Prestashop Cron Tasks Manager" by clicking this link' mod='obsstocks'}</a>
	{else}
		<br/><span style="color: red">{l s='You do not have installed the "Prestashop Cronjobs Module".' mod='obsstocks'}</span>
	{/if}
	
</div>