<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUWseNmm\AdminKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUWseNmm/AdminKernelProdContainer.php') {
    touch(__DIR__.'/ContainerUWseNmm.legacy');

    return;
}

if (!\class_exists(AdminKernelProdContainer::class, false)) {
    \class_alias(\ContainerUWseNmm\AdminKernelProdContainer::class, AdminKernelProdContainer::class, false);
}

return new \ContainerUWseNmm\AdminKernelProdContainer([
    'container.build_hash' => 'UWseNmm',
    'container.build_id' => '25a99d4c',
    'container.build_time' => 1757733980,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUWseNmm');
